## Basic Configuration

baseurl = "https://wizardly-bell-563959.netlify.app/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Bryan Clark"
title = "Clarklytics"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Bryan Clark"
intro = "Data is fun. "
description = "Design Thinker. Data Scientist @ Noom. MBA @ NYU Stern."
authorimage = "headshot.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,shiny,data,analytics"

## Social Accounts
[params.social]
github = "bclark86"
linkedin = "bryan-clark-b38470b"

## Extras
[params.extra]
copyright = "© 2020 clarklytcs.io"
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "/blog/"    
[[menu.main]]
    name = "shiny"
    identifier = "shiny"
    weight = 300
    url = "/shiny/"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    style = "pygments"
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"